### ISSUE TITLE
Maybe add Dragon Video System Hardware Specification to docs dir?

### ISSUE THREAD

**Issue by ninjalj** [hackerb9/vt340test#26] opened 2022-11-17 21:44 UTC
Hi,

Since the docs directory already contains most of the known documentation about the VT340 hardware, maybe:

http://www.bitsavers.org/pdf/dec/qbus/vcb02/Dragon_Video_System_Hardware_Specification_Rev_4.2_19850625.pdf

could be a good addition.

Other related docs are:

https://vt100.net/dec/ek-104aa-tm-001.pdf which describes the VCB02, a video subsystem for the MicroVAX workstation using the same chips (Adder and Viper) that the VT340 uses,

and

http://bitsavers.org/pdf/dec/semiconductor/1986_Digital_Semiconductor_Databook.pdf which in pages 2-001 to 2-074 has some documentation on the Adder and Viper chips.

**Comment by hackerb9** [comment] 2022-11-18 01:11
Oh, neat. I was reading some of these earlier but I didn't know how to tell which card card was actually used. For example, I've got a VT-340+G2 which was advertised as 33% faster graphics processing, but what exactly does that mean in terms of hardware?

And what's the relationship between Dragon, Adder, and Viper?

**Comment by ninjalj** [comment] 2022-11-18 02:33
In MP-02412 they are E70 and E85-E88 at pages 15 and 17, can be seen (with
round stickers) on
https://terminals-wiki.org/wiki/index.php/File:VT340_08.jpg

**Comment by hackerb9** [comment] 2022-11-18 05:56
Fascinating reading. 

I haven't read the Dragon book yet, but that VCB02 for microvax book is crammed with good information. It seems these chips had a lot of abilities that were never exposed via the VT340's API. I wonder if it'd be possible to make use of features like antialiased, proportional-width text and affine transformations. Even if it's not possible through the API, since the VT340's ROM was on a cartridge, perhaps a backdoor route can be found (or made). 

I'm guessing the ADDRess Processor is "Addr" and the VIdeo PRocessor is "ViPr", right? The VCB02 microvax book never uses the reptilian code names. It does sometimes refer to them as "DC 322/323".  The VT340 schematic ties them together, "DC 322" is the "VIPER, 68CRQD GULLWIN_".

> 8031C MICROPROCESSOR W/O P      2
> DC 322 VIPER, 68CRQD GULLWIN     4
> DC 323-CA ADDER II ZMOS                 1
> RAM, 64k x 4, DYNAMIC 15               26

(I presume "GULLWIN" was supposed to say "GULLWING" since all the component names are cut off at that column. Also, at the time the chip was designed, Back To The Future was a blockbuster and "gull-wing" cars were rad.)

Do you know how much the VCB02 documentation differs from what actually went into the VT340?

The system the microvax book describes is 8-bit pseudocolor which picks from a palette of 24-bit colors. The VT340 is a 4-bit pseudocolor system which picks from a palette of 12-bit colors. However, the book also mentions that a 4-bit system can be upgraded to 8-bit by adding another card. Was such upgradability ever envisioned for the VT340? Given that they actually slotted a ROM cartridge and split the circuit across multiple boards, it's possible they expected upgrades.[^1]

At the time the VCB02 microvax book was written, scrolling speed was limited by RAM, not the video processor. I wonder if that was still the case when the VT340 was released a year or two later. Could a RAM upgrade increase the VT340's speed? 

Thank you for these documents. I'll definitely add them, but first I have to run them through deskew and OCR. I'll put them in a "docs/hardware" subdirectory.   (Reminder to self: add a link to http://avitech.com.au/?page_id=1964, too.)

  [^1]: Though, now that I think on it, the ROM was more likely to be for international fonts and splitting the circuit might have just been the best they could do in 1987. By 1990, the VT340+ was released with a single circuit board and no ROM slot.

**Comment by ninjalj** [comment] 2022-11-19 23:08
> I'm guessing the ADDRess Processor is "Addr" and the VIdeo PRocessor is "ViPr", right? 

Yep. According to the Dragon specification, they were previously called "upper" and "lower".

> Do you know how much the VCB02 documentation differs from what actually went into the VT340?

Nope. 

> Thank you for these documents. I'll definitely add them, but first I have to run them through deskew and OCR. I'll put them in a "docs/hardware" subdirectory. (Reminder to self: add a link to http://avitech.com.au/?page_id=1964, too.)

The discussion in the SIMH mailing list linked from there is where I found the Dragon name for the video system.

**Comment by hackerb9** [comment] 2022-11-20 08:40
Okay, they've been [uploaded](https://github.com/hackerb9/vt340test/tree/main/docs/kindred/), deskewed and OCR'd. The databook was huge, so I extracted just the relevant section. 

Just for my own sanity, but also to double check, let's see if I got all these aliases correct.

DRAGON | VIPER | ADDER
-|-|-
Video subsystem<br/>(Vipers and Adder together) | Video processor<br/>(one bit plane per chip,<br/>comes in modules of 4)  | Address processor<br/>(one can control up to 8 Vipers)
_Aliases_ | |
VCB02  | Part name DC322 | Part name DC323
| | Part # 78660-GA<br/>(HMOS) | Part# 78690-GA<br/>(ZMOS)
| | Purchase # 21-21552-01 | Purchase # 21-21553-01 
| | Parallel processing of video data<br/>Display refresh, window scrolling, screen updates. Transfers data to and from bitmap memory.| Controls vipers.<br/>Scan timing, status generation, memory address generation for videodisplay refresh, issues scroll and update operations to vipers
_Next version_
| | SCVIPER<br/>(Standard Cell CMOS) |Dragon<br/>(ADDER II)
| | Part # 78680-GA |Part # 78690-GB
 
I don't know about the SCVIPER, but The ADDER II is what was used in the VT340 according to the schematic. Unfortunately, the 1986 databook only mentions that it is a "new product in development".  (Curiously, it refers to it as "Dragon (ADDER II)".)

**Closed** 2022-11-20 09:26 UTC

**Comment by ninjalj** [comment] 2022-11-21 00:35
The Dragon specification gives this definition in page 6:

> "Dragon" or "Dragon system" refers to the entire video system (with or without a local processor). "Chips" or "Dragon chips" refers only to the Adder and Viper chips. "Hardware"refers to all of the Dragon system EXCEPT the local processor and its firmware.

So, I guess that includes the colormap, shift registers and possibly one of the 8031s.

OTOH, AFAIU VCB02 refers strictly to the card for the MicroVAX using the Q22-Bus.

Regarding the different versions of the ADDER and VIPER, the SCVIPER seems to be simply  the faster CMOS version of the VIPER. See the 1986 databook:

>  The 78660 video processor is a 68-pin, HMOS VLSI version that provides a frame refresh rate of 60 Hz and has a power consumption of 1. 9 W. The 78680 video processor is a 68-pin, CMOS VLSI version that provides a frame refresh
rate of 80 Hz and has a power consumption of 0.5 W.

(Note that 80 Hz is a 33% improvement over 60 Hz, so if the VT340+ does 80 Hz, that would explain the advertised 33% faster graphic processing.)

https://gunkies.org/wiki/DEC_Semiconductor_Chips, lists it as Part Name DC502, Part Number 78680-GA, Purchase Number 21-25011-01, Description Video Processor (VIPER), giving a reference to the 1987 databook, which doesn't seem to have changed much from the 1986 version, mainly removing text references to 78660 (but the diagrams all still contain 78660).

The Dragon specification has an appendix "A - Dragon Chip Bugs and Changes", that talks about a Pass 2 Adder and Viper, designated as DC323B and DC322B, and also says that a bug in Pass 2 Viper will be fixed in Pass 3 Viper.

Assuming that passes correspond to the "variation" (https://gunkies.org/wiki/DEC_part_number) part in Purchase Numbers, the Engineering Drawings and the photos from avitech have: 

21-21553-02 DC323-CA ADDER II ZMOS
21-21552-05 DC322 VIPER, 68CRQD GULLWING

(CRQD is probably for CERQUAD, Ceramic Quad In-line Package, for Gullwing see https://workmanship.nasa.gov/lib/insp/2%20books/links/sections/707%20Gull-Wing%5EL%20Leaded%20Packages.html)

which would seem to indicate a Pass 2 Adder, and a Pass 5 Viper, but still the HMOS version.

As for the -GA suffix, the 1987 databook has the following:

> GA = Gullwing
> FA = Straight
> PA = Pin grid array

**Comment by hackerb9** [comment] 2022-11-21 18:09
> As for the -GA suffix, the 1987 databook has the following:
> 
> > GA = Gullwing
> > FA = Straight
> > PA = Pin grid array

Thanks for all the great detective work. I'm particularly glad to have the "GULLWIN" mystery solved, especially after seeing a post on the SIMH mailing list actually referring to the chip as "Viper Gullwin".

And thanks for correcting me that VCB02 is just one implementation of the Dragon system. Did DEC not publish manuals as exhaustive as the one we have for the VCB02 for other Dragon systems or is that all that remains from the dust of history? Were there many dragon systems created? I did a search for "4-plane or 8-plane DEC" and found people [selling the VS40X](https://www.ebay.com/itm/224903098545). It looks from the pictures like it has an adder and eight vipers. 

![VS40X](https://i.ebayimg.com/images/g/9ZkAAOSwKbFiPK~V/s-l1600.jpg)

**Comment by hackerb9** [comment] 2022-11-22 03:05
BTW, Sounds like the 1987 databook would be the one we'd want to cite for the VT340. Is there a reason for not using a later edition?

As for the speed increase, it's not the refresh rate. The original VT340 schematic lists the ADDER II as a component. Also, my VT340+ is able to receive data splatted to the screen at a slightly higher speed before needing XON/XOFF flow control, as compared to the numbers in the manual for a regular VT340. That could have to do with the ADDER since that handles scrolling, right? Or perhaps the whole system's clock rate was bumped up?

Presuming I'm even reading the schematics correctly, of course. The term "VT340**+**" doesn't appear in them. Instead it refers to VT340-A (original) and VT340-G (modified).

**Comment by ninjalj** [comment] 2022-11-23 00:00
Nice find on the VS40X.

> BTW, Sounds like the 1987 databook would be the one we'd want to cite for
> the VT340. Is there a reason for not using a later edition?
>
The 1986 version contains info on the 78660 Viper that the 1987 databook
doesn't have. I don't think, but I could be wrong, that the 1987 databook
contains any new info.

**Comment by hackerb9** [comment] 2022-11-24 20:23
I'm wondering if the VT340 has a 78660 or 78680. The Part Number in engineering drawings for the original VT340-A2 include part number 21-21552-05 which differs from the number given in the 1986 databook for the 78660, which ends in -01.

**Comment by ninjalj** [comment] 2022-11-24 23:20
> I'm wondering if the VT340 has a 78660 or 78680. The Part Number in
> engineering drawings for the original VT340-A2 include part number
> 21-21552-05 which differs from the number given in the 1986 databook for
> the 78660, which ends in -01.
>
> I guess that's still a 78660, but maybe 5th pass? Or some variant numbers
may have been reserved and eventually not used.

The 78680 seems to be 21-25011-01 according to the 1987 databook, and is
the chip used at the VS40X (21-25001-01 / DEC 502A / 78680-GA if I read
that correctly). I think the chip near the Vipers at the bottom is
(21-24071-01 / DEC 500A / 78640-GA), which would make it "Dragon Timing
Chip (DTC) - Semicustom video device for color timing" according to the
1986 databook, and probably the chip above it with a round sticker is an
Adder.

**Comment by hackerb9** [comment] 2022-11-25 18:04
Thank you. Unfortunately, I tried looking into that part number and now I'm even more confused. The 1987 databook (vol. 1) indicates that the 78680 is HMOS, but I thought the 1986 databook had said it was going to be CMOS. Volume 2 of the 1987 databook is supposed to have all the CMOS devices, but no vipers or adders are listed in it. If the '80 is still HMOS, then how is it different from the '60?

**Comment by ninjalj** [comment] 2022-11-25 21:38
> Thank you. Unfortunately, I tried looking into that part number and now
> I'm even more confused. The 1987 databook (vol. 1) indicates that the 78680
> is HMOS, but I thought the 1986 databook had said it was going to be CMOS.
>
That's probably an oversight in the editing process. The description at the
start of chapter 2 seems to come from the 1986 edition, with the reference
to 78660 deleted.

**Comment by hackerb9** [comment] 2022-11-29 09:45
It looks like the purchase number for the Viper on the VS40X is 21-25011-01, not 21-25001-01, at least according to "[birdman86](https://commons.wikimedia.org/wiki/User:Birdman86)" who took a [picture of the 78680](https://commons.wikimedia.org/wiki/File:DEC_78680_die.JPG) and [78690 dies](https://commons.wikimedia.org/wiki/File:DEC_78690_die.JPG).

**Comment by ninjalj** [comment] 2022-11-30 21:33
> It looks like the purchase number for the Viper on the VS40X is 21-25011-01, not 21-25001-01,

Yep, 25001 was a typo. The photo clearly shows 25011.

**Comment by hackerb9** [comment] 2022-12-01 06:03
I found the schematics for the VS40X 4-plane color from 1987 and got more info:

    https://archive.org/details/bitsavers_decvax410M_19937590/page/n88/mode/1up?q=viper

Instead of referring to 25011 as the "SCVIPER" as the 1987 databook does, it calls it "VIPER 80HZ,CMOS-I VIDEO PROCESSO". The part name is still "DC502".

Additionally, this is the second schematic I've found that refers to the 21553 as "DC 323-CA". I have not seen any other references to "DC323C" except that given by Birdman86 to his photo of the CPU die. Do you know if it is a typo, or if perhaps -CA had some meaning similar to -GA?

**Comment by ninjalj** [comment] 2022-12-10 00:26
> I found the schematics for the VS40X 4-plane color from 1987 and got more
> info:
>
> https://archive.org/details/bitsavers_decvax410M_19937590/page/n88/mode/1up?q=viper
>
> Nice find!

> Instead of referring to 25011 as the "SCVIPER" as the 1987 databook does,
> it calls it "VIPER 80HZ,CMOS-I VIDEO PROCESSO". The part name is still
> "DC502".
>
> I think SCVIPER just means Standard cell CMOS VIPER, as opposed to the
earlier HMOS VIPER.

> Additionally, this is the second schematic I've found that refers to the
> 21553 as "DC 323-CA". I have not seen any other references to "DC323C"
> except that given by Birdman86 to his photo of the CPU die. Do you know if
> it is a typo, or if perhaps -CA had some meaning similar to -GA?
>
No idea. sorry.

**Comment by hackerb9** [comment] 2022-12-14 18:14
> I think SCVIPER just means Standard cell CMOS VIPER, as opposed to the
> earlier HMOS VIPER.

Makes sense to me. Now I'm curious if DEC ever made more CMOS VIPERs or if "SCVIPER" always means 21-25011-01. Any suggestions for where you'd look to find out?

I'm having the darnedest time finding versions of the Semiconductor Databook beyond 1987.  According to the [Computer History Museum](https://www.computerhistory.org/collections/catalog/102737681), DEC's Semiconductor Operations group (SCO) kept publishing guides at least until 1992.
